### ISSUE TITLE
Unexpected Error When Preprocessing

### ISSUE THREAD

**Issue by HMJiangGatech** [google/airdialogue_model#7]
After I run `bash scripts/preprocess.sh -p train`, I got the following error:

mode = airdialogue
word cutoff = 10
nltk data path = ./data/nltk
data path = ./data/airdialogue
partition = train
json path = ./data/airdialogue/json
tokenized path = ./data/airdialogue/tokenized
tokenizing train data...
2020-05-18 20:39:43.271598: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
loading data: 642868it [04:13, 2532.79it/s]
process kb: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 321459/321459 [01:57<00:00, 2728.20it/s]
process raw data:   0%|                                                                                                                                                  | 0/321459 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/bin/airdialogue", line 4, in <module>
    __import__('pkg_resources').run_script('airdialogue==0.1', 'airdialogue')
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1471, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/conda/lib/python3.7/site-packages/airdialogue-0.1-py3.7.egg/EGG-INFO/scripts/airdialogue", line 33, in <module>
  File "/opt/conda/lib/python3.7/site-packages/airdialogue-0.1-py3.7.egg/airdialogue/prepro/prepro_main.py", line 276, in main
  File "/opt/conda/lib/python3.7/site-packages/airdialogue-0.1-py3.7.egg/airdialogue/prepro/prepro_main.py", line 162, in load_data_from_jsons
  File "/opt/conda/lib/python3.7/site-packages/airdialogue-0.1-py3.7.egg/airdialogue/prepro/tokenize_lib.py", line 359, in process_main_data
  File "/opt/conda/lib/python3.7/site-packages/airdialogue-0.1-py3.7.egg/airdialogue/prepro/tokenize_lib.py", line 286, in get_dialogue_boundary
AssertionError: start token appeared twice: <t1> Hello <t2> Hello <t2> How may I help you ? <t1> Can you help me to change my recent reservation because my trip dates are got postponed ? <t2> I will help you with that please share your name to proceed further ? <t1> Edward hall here . <t2> Please wait for a while . <t1> Sure , take your own time . <t2> There is no active reservation found under your name to amend it . <t1> That 's ok , thank you for checking . <t2> Thank you for choosing us . <eod> <t1>

Is that because of python3?

**Comment by josephch405** [comment]
As noted in conversation, we will fix this issue with a new data release.

**Comment by josephch405** [comment]
This should be fixed with the new data release.

**Comment by aman229** [comment]
@josephch405 Has this been fixed? Because I am still getting this bug.

**Comment by josephch405** [comment]
Try redownloading the data zip from the readme - this was an issue that occurred when using old data.
